name: Test Build

on:
    # push:
    #     branches: [ 'master' ]
    workflow_dispatch:

env:
    BUILD_TYPE: Debug

jobs:
    build:
        env:
            buildDir: '${{ github.workspace }}/build/'
        strategy:
            matrix:
                os: [ macos-10.15, windows-2019, ubuntu-18.04 ]
            fail-fast: false
        runs-on: ${{ matrix.os }}

        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: true

            -   name: Checkout LFS objects
                run: git lfs pull

            -   uses: maxim-lobanov/setup-xcode@v1
                with:
                    xcode-version: '11.2.1'
                if: runner.os == 'macOS'

            -   name: Install tools on Ubuntu
                run: sudo apt-get install -y ninja-build build-essential libcurl4-openssl-dev
                if: runner.os == 'Linux'

            # Install latest CMake.
            -   uses: lukka/get-cmake@latest

            -   name: Set up Visual Studio shell
                if: runner.os == 'Windows'
                uses: egor-tensin/vs-shell@v2

            -   name: Build the projo   ect (Windows)
                if: runner.os == 'Windows'
                run: |
                    cmake -B build -G "Ninja"
                    cmake --build build --target RunFrameworkTests

            -   name: Build the project
                if: runner.os != 'Windows'
                run: |
                    cmake -B build
                    cmake --build build --target RunFrameworkTests
