name: Check code style

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  check_style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Check if the adheres to the standard style
      run: |
        RESULT=$(scripts/check_style.sh)
        CODE=$?
        if [ $CODE -ne 0 ]; then
          curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"$RESULT\"}" https://discord.com/api/webhooks/882340318798835762/Zpxb3qDpwukl2QJ_PrtZ1lxbkmRpVJlhza0QxO1JA9VeD6Zhqqn-5aFVVEaptN1LV6WG
        fi
